# `Shore` GoReleaser configurations.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    - go mod vendor
    - go mod tidy
builds:
  - main: ./cmd/shore/shore.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^examples:'
