# This file is used as a base for .goreleaser for easy releasing.
# The image is intended to be used as a standalone "product"
FROM scratch
LABEL maintainer="shore@autodesk.com"

ENTRYPOINT ["/jt"]
COPY jsonnet-test /jt
